"""
core/aliases.py
Mapeia o nome de import usado no código para o nome normalizado do pacote
declarado em requirements.txt / pyproject.toml.

Problema: muitos pacotes são instalados com um nome (PyPI) mas importados
com outro.  Exemplos clássicos:
    import PIL         → pacote: Pillow
    import cv2         → pacote: opencv-python
    import sklearn     → pacote: scikit-learn

Sem esse mapa, o zombie_analyzer marcaria esses pacotes como "zumbis"
(declarados mas nunca importados), o que seria um falso-positivo.

Uso:
    from core.aliases import IMPORT_TO_PACKAGE

    pkg_name = IMPORT_TO_PACKAGE.get(import_name, import_name)
"""
from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Mapa canônico  import_name → package_name  (ambos normalizados)
# Convenção: chaves e valores em lowercase, hífens convertidos a underscores.
# ---------------------------------------------------------------------------
_RAW_ALIASES: dict[str, str] = {
    # Imagem / visão computacional
    "PIL":           "pillow",
    "cv2":           "opencv_python",
    "skimage":       "scikit_image",
    # Machine learning / data science
    "sklearn":       "scikit_learn",
    "bs4":           "beautifulsoup4",
    "dateutil":      "python_dateutil",
    "dotenv":        "python_dotenv",
    "yaml":          "pyyaml",
    "ujson":         "ujson",
    "attr":          "attrs",
    "google.cloud":  "google_cloud",
    "gi":            "pygobject",
    "usb":           "pyusb",
    "serial":        "pyserial",
    "Crypto":        "pycryptodome",
    "OpenSSL":       "pyopenssl",
    "jwt":           "pyjwt",
    "jose":          "python_jose",
    "pkg_resources": "setuptools",
    "pkg":           "setuptools",
    "setuptools":    "setuptools",
    "distutils":     "setuptools",
    "docutils":      "docutils",
    "magic":         "python_magic",
    "MySQLdb":       "mysql_connector_python",
    "psycopg2":      "psycopg2_binary",
    "pymysql":       "pymysql",
    "wx":            "wxpython",
    "gi.repository": "pygobject",
    "win32com":      "pywin32",
    "win32api":      "pywin32",
    "pythoncom":     "pywin32",
    "pywintypes":    "pywin32",
    "gtk":           "pygobject",
    "glib":          "pygobject",
    "gobject":       "pygobject",
    "gio":           "pygobject",
    "atk":           "pygobject",
    "pango":         "pygobject",
    "cairo":         "pycairo",
    "nacl":          "pynacl",
    "Levenshtein":   "python_levenshtein",
    "fitz":          "pymupdf",
    "docx":          "python_docx",
    "pptx":          "python_pptx",
    "xlrd":          "xlrd",
    "xlwt":          "xlwt",
    "openpyxl":      "openpyxl",
    "odf":           "odfpy",
    "netaddr":       "netaddr",
    "netifaces":     "netifaces",
    "scapy":         "scapy",
    "impacket":      "impacket",
    "ldap":          "python_ldap",
    "ldap3":         "ldap3",
    "saml2":         "pysaml2",
    "onelogin":      "python3_saml",
    "spacy":         "spacy",
    "gensim":        "gensim",
    "nltk":          "nltk",
    "transformers":  "transformers",
    "torch":         "torch",
    "tensorflow":    "tensorflow",
    "keras":         "keras",
    "mx":            "mxnet",
    "mxnet":         "mxnet",
    "jax":           "jax",
    "flax":          "flax",
    "optax":         "optax",
    "haiku":         "dm_haiku",
    "trax":          "trax",
    "paddle":        "paddlepaddle",
    "onnx":          "onnx",
    "onnxruntime":   "onnxruntime",
    "xgboost":       "xgboost",
    "lightgbm":      "lightgbm",
    "catboost":      "catboost",
    "shap":          "shap",
    "lime":          "lime",
    "eli5":          "eli5",
    "mlflow":        "mlflow",
    "wandb":         "wandb",
    "optuna":        "optuna",
    "ray":           "ray",
    "dask":          "dask",
    "modin":         "modin",
    "vaex":          "vaex",
    "cudf":          "cudf",
    "cuml":          "cuml",
    "numba":         "numba",
    "cython":        "cython",
    "cffi":          "cffi",
    "ctypes":        "ctypes",
    "swig":          "swig",
    "pybind11":      "pybind11",
    "zmq":           "pyzmq",
    "msgpack":       "msgpack",
    "bson":          "pymongo",
    "gridfs":        "pymongo",
    "motor":         "motor",
    "elasticsearch": "elasticsearch",
    "cassandra":     "cassandra_driver",
    "aerospike":     "aerospike",
    "couchdb":       "couchdb",
    "neo4j":         "neo4j",
    "py2neo":        "py2neo",
    "neomodel":      "neomodel",
    "arango":        "python_arango",
    "influxdb":      "influxdb",
    "prometheus_client": "prometheus_client",
    "opentelemetry": "opentelemetry_api",
    "grpc":          "grpcio",
    "protobuf":      "protobuf",
    "thrift":        "thrift",
    "avro":          "avro",
    "kafka":         "kafka_python",
    "confluent_kafka": "confluent_kafka",
    "pika":          "pika",
    "nats":          "nats_py",
    "aio_pika":      "aio_pika",
    "kombu":         "kombu",
    "celery":        "celery",
    "dramatiq":      "dramatiq",
    "rq":            "rq",
    "apscheduler":   "apscheduler",
    "schedule":      "schedule",
    "arrow":         "arrow",
    "pendulum":      "pendulum",
    "babel":         "babel",
    "pytz":          "pytz",
    "tzlocal":       "tzlocal",
    "humanize":      "humanize",
    "tabulate":      "tabulate",
    "tqdm":          "tqdm",
    "alive_progress": "alive_progress",
    "rich":          "rich",
    "click":         "click",
    "typer":         "typer",
    "fire":          "fire",
    "docopt":        "docopt",
    "argcomplete":   "argcomplete",
    "loguru":        "loguru",
    "structlog":     "structlog",
    "colorlog":      "colorlog",
    "colorama":      "colorama",
    "termcolor":     "termcolor",
    "blessed":       "blessed",
    "asciimatics":   "asciimatics",
    "urwid":         "urwid",
    "npyscreen":     "npyscreen",
    "prompt_toolkit": "prompt_toolkit",
    "pygments":      "pygments",
    "jinja2":        "jinja2",
    "mako":          "mako",
    "chameleon":     "chameleon",
    "genshi":        "genshi",
    "lxml":          "lxml",
    "html5lib":      "html5lib",
    "htmlparser":    "html5lib",
    "markdown":      "markdown",
    "mistune":       "mistune",
    "bleach":        "bleach",
    "pydantic":      "pydantic",
    "marshmallow":   "marshmallow",
    "cerberus":      "cerberus",
    "voluptuous":    "voluptuous",
    "jsonschema":    "jsonschema",
    "schematics":    "schematics",
    "wtforms":       "wtforms",
    "deform":        "deform",
    "colander":      "colander",
    "formencode":    "formencode",
    "passlib":       "passlib",
    "bcrypt":        "bcrypt",
    "argon2":        "argon2_cffi",
    "itsdangerous":  "itsdangerous",
    "authlib":       "authlib",
    "oauthlib":      "oauthlib",
    "requests_oauthlib": "requests_oauthlib",
    "google_auth":   "google_auth",
    "msal":          "msal",
    "okta":          "okta",
    "boto3":         "boto3",
    "botocore":      "botocore",
    "s3transfer":    "s3transfer",
    "azure":         "azure",
    "google":        "google_cloud",
    "googleapiclient": "google_api_python_client",
    "tweepy":        "tweepy",
    "slack_sdk":     "slack_sdk",
    "discord":       "discord_py",
    "telethon":      "telethon",
    "pyrogram":      "pyrogram",
    "vk":            "vk_api",
    "stripe":        "stripe",
    "paypalrestsdk": "paypalrestsdk",
    "braintree":     "braintree",
    "sendgrid":      "sendgrid",
    "mailchimp3":    "mailchimp3",
    "twilio":        "twilio",
    "vonage":        "vonage",
    "plivo":         "plivo",
    "nexmo":         "vonage",
    "geocoder":      "geocoder",
    "geopy":         "geopy",
    "folium":        "folium",
    "geopandas":     "geopandas",
    "shapely":       "shapely",
    "fiona":         "fiona",
    "pyproj":        "pyproj",
    "rasterio":      "rasterio",
    "gdal":          "gdal",
    "osgeo":         "gdal",
    "mapbox":        "mapboxgl",
    "pydeck":        "pydeck",
    "kepler":        "keplergl",
    "ipyleaflet":    "ipyleaflet",
    "bokeh":         "bokeh",
    "altair":        "altair",
    "plotly":        "plotly",
    "matplotlib":    "matplotlib",
    "seaborn":       "seaborn",
    "ggplot":        "plotnine",
    "plotnine":      "plotnine",
    "dash":          "dash",
    "panel":         "panel",
    "holoviews":     "holoviews",
    "hvplot":        "hvplot",
    "datashader":    "datashader",
    "param":         "param",
    "streamlit":     "streamlit",
    "gradio":        "gradio",
    "nicegui":       "nicegui",
    "solara":        "solara",
    "voila":         "voila",
    "ipywidgets":    "ipywidgets",
    "ipython":       "ipython",
    "jupyter":       "jupyter",
    "nbformat":      "nbformat",
    "nbconvert":     "nbconvert",
    "nbclient":      "nbclient",
    "papermill":     "papermill",
    "ploomber":      "ploomber",
    "prefect":       "prefect",
    "airflow":       "apache_airflow",
    "luigi":         "luigi",
    "kedro":         "kedro",
    "metaflow":      "metaflow",
    "zenml":         "zenml",
    "bentoml":       "bentoml",
    "seldon":        "seldon",
    "kfp":           "kfp",
    "feast":         "feast",
    "great_expectations": "great_expectations",
    "pandera":       "pandera",
    "evidently":     "evidently",
    "whylogs":       "whylogs",
    "deepchecks":    "deepchecks",
    "pytest":        "pytest",
    "unittest":      "unittest",
    "nose":          "nose",
    "hypothesis":    "hypothesis",
    "faker":         "faker",
    "factory_boy":   "factory_boy",
    "responses":     "responses",
    "httpretty":     "httpretty",
    "vcrpy":         "vcrpy",
    "freezegun":     "freezegun",
    "time_machine":  "time_machine",
    "moto":          "moto",
    "localstack":    "localstack",
    "testcontainers": "testcontainers",
    "docker":        "docker",
    "kubernetes":    "kubernetes",
    "ansible":       "ansible",
    "fabric":        "fabric",
    "invoke":        "invoke",
    "nox":           "nox",
    "tox":           "tox",
    "coverage":      "coverage",
    "mypy":          "mypy",
    "pyright":       "pyright",
    "pylint":        "pylint",
    "flake8":        "flake8",
    "ruff":          "ruff",
    "black":         "black",
    "isort":         "isort",
    "bandit":        "bandit",
    "safety":        "safety",
    "semgrep":       "semgrep",
    "pre_commit":    "pre_commit",
    "commitizen":    "commitizen",
    "bumpversion":   "bumpversion",
    "twine":         "twine",
    "build":         "build",
    "flit":          "flit",
    "poetry":        "poetry",
    "hatch":         "hatch",
    "pdm":           "pdm",
    "pip":           "pip",
    "setuptools":    "setuptools",
    "wheel":         "wheel",
    "conda":         "conda",
    "mamba":         "mamba",
    "pixi":          "pixi",
    "uv":            "uv",
}


def _normalize(name: str) -> str:
    """Normaliza um nome de import ou pacote (lowercase, hífens/pontos → underscores)."""
    # Pega apenas o nome raiz  (ex: "google.cloud.storage" → "google")
    root = name.split(".")[0]
    return re.sub(r"[-_.]+", "_", root).lower()


# Dicionário público com chaves e valores normalizados.
IMPORT_TO_PACKAGE: dict[str, str] = {
    _normalize(k): _normalize(v) for k, v in _RAW_ALIASES.items()
}


def resolve_import(import_name: str) -> str:
    """
    Dado um nome de import (ex: ``"PIL"``), retorna o nome normalizado do pacote
    PyPI correspondente.  Se não houver alias, devolve o próprio nome normalizado.

    Args:
        import_name: Nome raiz do módulo importado (ex: ``"PIL"``, ``"cv2"``).

    Returns:
        Nome normalizado do pacote PyPI (ex: ``"pillow"``, ``"opencv_python"``).

    Examples:
        >>> resolve_import("PIL")
        'pillow'
        >>> resolve_import("requests")
        'requests'
    """
    normalized = _normalize(import_name)
    return IMPORT_TO_PACKAGE.get(normalized, normalized)
